name: Deploy One Solution (Worker)
run-name: Deploy ${{ inputs.solution_group }} -> ${{ inputs.app_name }} to ${{ inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      solution_group:
        description: 'Solution group name'
        required: true
        type: string
      app_name:
        description: 'App name to deploy'
        required: true
        type: string
      environment:
        description: 'Target environment'
        required: true
        type: string

permissions:
  contents: read

jobs:
  DeployOneSolution:
    environment: ${{ inputs.environment }}
    name: Deploy ${{ inputs.solution_group }} -> ${{ inputs.app_name }} to ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v5.0.0
        with:
          fetch-depth: 1
        env:
          GIT_LFS_SKIP_SMUDGE: 1

      - name: Install Power Platform Tools
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: Pull only needed LFS files
        run: git lfs pull --include="SolutionGroups/${{ inputs.solution_group }}/${{ inputs.app_name }}.zip"

      - name: Detect deployment setting file
        id: detect
        run: |
          echo "Detecting if deployment settings file exists..."
          DEPLOYMENT_SETTINGS_FILE="SolutionGroups/${{ inputs.solution_group }}/${{ inputs.app_name }}.${{ inputs.environment }}.json"
          if [ -f "$DEPLOYMENT_SETTINGS_FILE" ]; then
            echo "Found deployment settings file: $DEPLOYMENT_SETTINGS_FILE"
            echo "deployment_settings_file=$DEPLOYMENT_SETTINGS_FILE" >> $GITHUB_OUTPUT
            echo "use_deployment_settings=true" >> $GITHUB_OUTPUT
          else
            echo "No deployment settings file found."
            echo "deployment_settings_file=" >> $GITHUB_OUTPUT
            echo "use_deployment_settings=false" >> $GITHUB_OUTPUT
          fi

      - name: Import managed solution
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ secrets.ENVIRONMENT_URL }}
          app-id: ${{ secrets.CLIENT_ID }}
          client-secret: ${{ secrets.CLIENT_SECRET }}
          tenant-id: ${{ secrets.TENANT_ID }}
          solution-file: '${{ inputs.solution_group }}/${{ inputs.app_name }}.zip'
          working-directory: './SolutionGroups/'
          deployment-settings-file: ${{ steps.detect.outputs.deployment_settings_file }}
          use-deployment-settings-file: ${{ steps.detect.outputs.use_deployment_settings }}
          publish-changes: true
